services:
  auth-mongo:
    image: mongo:6
    container_name: auth-mongo
    ports:
      - "27018:27017"
    volumes:
      - auth-mongo-vol:/data/db
    networks:
      - zest-net

  data-mongo:
    image: mongo:6
    container_name: data-mongo
    ports:
      - "27019:27017"
    volumes:
      - data-mongo-vol:/data/db
    networks:
      - zest-net

  redis:
    image: redis:7
    container_name: redis
    networks:
      - zest-net

  orion:
    image: fiware/orion:latest
    container_name: orion
    ports:
      - "1026:1026"
    command:
      - "-dbURI"
      - "mongodb://data-mongo:27017/datadb"
      - "-port"
      - "1026"
      - "-logLevel"
      - "INFO"
    depends_on:
      - data-mongo
    networks:
      - zest-net

  backend:
    build:
      context: ./backend
    container_name: zest-backend
    env_file: ./backend/.env
    depends_on:
      - data-mongo
      - auth-mongo
      - redis
    ports:
      - "4000:4000"
    networks:
      - zest-net
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zest-frontend
    environment:
      - REACT_APP_API_URL=http://backend:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - zest-net
      
volumes:
  auth-mongo-vol:
  data-mongo-vol:

networks:
  zest-net:
    driver: bridge
