version: "3.8"

services:
  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - fiware

  orion:
    image: fiware/orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-db:27017
    networks:
      - fiware

networks:
  fiware:
